name: cicd pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:

  # -------------------------
  # Job 1: Build and Test
  # -------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application tests
        run: pytest


  # -------------------------
  # Job 2: Docker
  # -------------------------
  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image version
        run: echo "IMAGE_VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }} .

      - name: Security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Run Docker container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name ci-pipeline \
            end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }}

      - name: Health check
        run: |
          for i in {1..30}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' ci-pipeline)

            if [ "$status" = "healthy" ]; then
              echo "Container is healthy"
              break
            fi

            if [ "$status" = "unhealthy" ]; then
              echo "Container is unhealthy"
              exit 1
            fi

            echo "Container is still starting..."
            sleep 2
          done

          if [ "$status" != "healthy" ]; then
            echo "Container did not become healthy"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag image
        run: |
          docker tag \
            end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }} \
            ${{ steps.login-ecr.outputs.registry }}/end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }}

      - name: Push image to ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }}


  # -------------------------
  # Job 3: Deployment
  # -------------------------
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image version
        run: echo "IMAGE_VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition cicd-task \
            --query taskDefinition > task-definition.json

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: cicd-container
          image: ${{ steps.login-ecr.outputs.registry }}/end-to-end-cicd-pipeline:${{ env.IMAGE_VERSION }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: cicd-task-service-nfiwv059
          cluster: cicd-cluster
          wait-for-service-stability: true